In [1]:
import pandas as pd
df = pd.read_csv(r'C:\WORK_IAAC\submissions\Storytelling\fiesta_shapefiles\fiestasbyprovince.csv')
df.head()

,Unnamed: 0,province,fest_name,date_start,date_fin,localidad,lat,lng
0,0,Álava,Fiestas de la Blanca,4,9 agosto,Vitoria,17.02621,74.37124
1,1,Albacete,La Feria,7,17 septiembre,Albacete,38.99793,-1.85292
2,2,Alicante,Moros y Cristianos,23,25 abril,Alcoy,38.36861,-0.43566
3,3,Almería,La Feria,20,27 agosto,Almería,36.84191,-2.46362
4,4,Asturias,Descenso del Sella,5,7 agosto,Arriondas. ribadesella,10.62720,123.77327

In [4]:
df = df.drop('Unnamed: 0', axis=1)

df.head()

,province,fest_name,date_start,date_fin,localidad,lat,lng
0,Álava,Fiestas de la Blanca,4,9 agosto,Vitoria,17.02621,74.37124
1,Albacete,La Feria,7,17 septiembre,Albacete,38.99793,-1.85292
2,Alicante,Moros y Cristianos,23,25 abril,Alcoy,38.36861,-0.43566
3,Almería,La Feria,20,27 agosto,Almería,36.84191,-2.46362
4,Asturias,Descenso del Sella,5,7 agosto,Arriondas. ribadesella,10.62720,123.77327