In [13]:
import pandas as pd
data = pd.read_csv(r'C:\WORK_IAAC\submissions\Storytelling\fiesta_shapefiles\fiestasWiki_national.csv')
data.head()

,festival,localidad,lat,date_start,est
0,El Bautizo del Niño,Palencia,"42°01′00″N 4°32′00″O﻿ / ﻿42.01667, -4.53333﻿",1 de enero,5 de marzo de 2015
1,La Vijanera,Silió(Cantabria),"43°08′53″N 4°01′17″O﻿ / ﻿43.14806, -4.02139﻿",2-8 de enero (primer domingo de enero después ...,28 de mayo de 2009
2,Cabalgata de Reyes Magos de Alcoy,Alcoy(Alicante),"38°41′54″N 0°28′25″O﻿ / ﻿38.69833, -0.47361﻿",5 de enero,28 de noviembre de 2001
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar(Cantabria),"43°23′36″N 4°06′17″O﻿ / ﻿43.39333, -4.10472﻿",5 de enero,23 de noviembre de 2009
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,"37°46′11″N 3°47′20″O﻿ / ﻿37.76972, -3.78889﻿",Noche del 16 de enero,2019

In [14]:
prov_list = []
for index, row in data.iterrows():
    if '(' in row['localidad']:
        prov = row['localidad'].split('(')[1].replace(')', '').strip()
    else:
        prov = row['localidad']
    prov_list.append(prov)
    row['localidad'] = row['localidad'].split('(')[0].strip()
data['prov'] = prov_list

data.head()

,festival,localidad,lat,date_start,est,prov
0,El Bautizo del Niño,Palencia,"42°01′00″N 4°32′00″O﻿ / ﻿42.01667, -4.53333﻿",1 de enero,5 de marzo de 2015,Palencia
1,La Vijanera,Silió,"43°08′53″N 4°01′17″O﻿ / ﻿43.14806, -4.02139﻿",2-8 de enero (primer domingo de enero después ...,28 de mayo de 2009,Cantabria
2,Cabalgata de Reyes Magos de Alcoy,Alcoy,"38°41′54″N 0°28′25″O﻿ / ﻿38.69833, -0.47361﻿",5 de enero,28 de noviembre de 2001,Alicante
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar,"43°23′36″N 4°06′17″O﻿ / ﻿43.39333, -4.10472﻿",5 de enero,23 de noviembre de 2009,Cantabria
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,"37°46′11″N 3°47′20″O﻿ / ﻿37.76972, -3.78889﻿",Noche del 16 de enero,2019,Jaén

In [15]:
data['lat'] = data['lat'].astype(str)

data[['Latitude', 'Longitude']] = data['lat'].dropna().apply(lambda x: pd.Series(x.split('/')[0:2]) if '/' in x else pd.Series([None, None]))

data = data.drop(columns=['lat'])
data.head()

,festival,localidad,date_start,est,prov,Latitude,Longitude
0,El Bautizo del Niño,Palencia,1 de enero,5 de marzo de 2015,Palencia,42°01′00″N 4°32′00″O﻿,"﻿42.01667, -4.53333﻿"
1,La Vijanera,Silió,2-8 de enero (primer domingo de enero después ...,28 de mayo de 2009,Cantabria,43°08′53″N 4°01′17″O﻿,"﻿43.14806, -4.02139﻿"
2,Cabalgata de Reyes Magos de Alcoy,Alcoy,5 de enero,28 de noviembre de 2001,Alicante,38°41′54″N 0°28′25″O﻿,"﻿38.69833, -0.47361﻿"
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar,5 de enero,23 de noviembre de 2009,Cantabria,43°23′36″N 4°06′17″O﻿,"﻿43.39333, -4.10472﻿"
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,Noche del 16 de enero,2019,Jaén,37°46′11″N 3°47′20″O﻿,"﻿37.76972, -3.78889﻿"

In [46]:
data.keys()

Index(['festival', 'localidad', 'date_start', 'est', 'prov', 'Latitude',
       'Longitude'],
      dtype='object')

In [16]:
import re

In [17]:
data['Longitude']

0         ﻿42.01667, -4.53333﻿
1         ﻿43.14806, -4.02139﻿
2         ﻿38.69833, -0.47361﻿
3         ﻿43.39333, -4.10472﻿
4         ﻿37.76972, -3.78889﻿
                ...
157       ﻿43.15361, -4.62333﻿
158       ﻿38.74500, -0.44056﻿
159     ﻿40.482194, -3.371861﻿
160       ﻿41.33056, -5.08139﻿
161       ﻿38.61667, -1.11667﻿
Name: Longitude, Length: 162, dtype: object

In [18]:
data = data.drop(columns=['Latitude'])
data[['lat', 'lng']] = data['Longitude'].dropna().apply(lambda x: pd.Series(x.split(',')) if ',' in x else pd.Series([None, None]))
data = data.drop(columns=['Longitude'])
data.head()

,festival,localidad,date_start,est,prov,lat,lng
0,El Bautizo del Niño,Palencia,1 de enero,5 de marzo de 2015,Palencia,﻿42.01667,-4.53333﻿
1,La Vijanera,Silió,2-8 de enero (primer domingo de enero después ...,28 de mayo de 2009,Cantabria,﻿43.14806,-4.02139﻿
2,Cabalgata de Reyes Magos de Alcoy,Alcoy,5 de enero,28 de noviembre de 2001,Alicante,﻿38.69833,-0.47361﻿
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar,5 de enero,23 de noviembre de 2009,Cantabria,﻿43.39333,-4.10472﻿
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,Noche del 16 de enero,2019,Jaén,﻿37.76972,-3.78889﻿

In [19]:
if data['lng'].str.contains('\ufeff').any():
    print("The 'lng' column contains the \\ufeff character")
else:
    print("The 'lng' column does not contain the \\ufeff character")
count = sum(data['lat'].astype(str).str.contains('\ufeff'))
count2 = sum(data['lng'].astype(str).str.contains('\ufeff'))
# print the count
print(count, count2)

The 'lng' column contains the \ufeff character
161 161

In [51]:
data.keys()

Index(['festival', 'localidad', 'date_start', 'est', 'prov', 'lat', 'lng'], dtype='object')

In [20]:
data['est'] = data['est'].str.rsplit(' ', 2).str[-1].fillna('1980')

In [21]:
data.head()

,festival,localidad,date_start,est,prov,lat,lng
0,El Bautizo del Niño,Palencia,1 de enero,2015,Palencia,﻿42.01667,-4.53333﻿
1,La Vijanera,Silió,2-8 de enero (primer domingo de enero después ...,2009,Cantabria,﻿43.14806,-4.02139﻿
2,Cabalgata de Reyes Magos de Alcoy,Alcoy,5 de enero,2001,Alicante,﻿38.69833,-0.47361﻿
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar,5 de enero,2009,Cantabria,﻿43.39333,-4.10472﻿
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,Noche del 16 de enero,2019,Jaén,﻿37.76972,-3.78889﻿

In [22]:
import re
data['latitude'] = data['lat'].apply(lambda x:re.findall(r'[0-9]+\.[0-9]+', str(x)))
data['latitude'] = data['latitude'].apply(lambda x:x[0] if len(x)>0 else None)

data['latitude'].head()

0    42.01667
1    43.14806
2    38.69833
3    43.39333
4    37.76972
Name: latitude, dtype: object

In [23]:
data['longitude'] = data['lng'].apply(lambda x:re.findall(r'\-[0-9]+\.[0-9]+', str(x)))
data['longitude'] = data['longitude'].apply(lambda x:x[0] if len(x)>0 else None)
data = data.drop(columns=['lat','lng'])
data.head()

,festival,localidad,date_start,est,prov,latitude,longitude
0,El Bautizo del Niño,Palencia,1 de enero,2015,Palencia,42.01667,-4.53333
1,La Vijanera,Silió,2-8 de enero (primer domingo de enero después ...,2009,Cantabria,43.14806,-4.02139
2,Cabalgata de Reyes Magos de Alcoy,Alcoy,5 de enero,2001,Alicante,38.69833,-0.47361
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar,5 de enero,2009,Cantabria,43.39333,-4.10472
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,Noche del 16 de enero,2019,Jaén,37.76972,-3.78889

In [24]:
data['date_start'].unique()

array(['1 de enero',
       '2-8 de enero (primer domingo de enero después de Año Nuevo)',
       '5 de enero', 'Noche del 16 de enero', '16, 17 y 18 de enero',
       '19 y 20 de enero', '20 y 21 de enero',
       '25-31 de enero (último domingo de enero)',
       '11 de enero-15 de febrero al 8 de febrero-14 de marzo (Carnaval)',
       '18 de enero-1 de marzo al 9 de febrero-12 de marzo (Carnaval)',
       '21 de enero-25 de febrero al 8 de febrero-14 de marzo (Carnaval)',
       '24 de enero-28 de febrero al 4 de febrero-10 de marzo (Carnaval)',
       '24 de enero-28 de febrero (sábado anterior a Carnaval)',
       '25 de enero-29 de febrero (domingo anterior a Carnaval)',
       '29 de enero-4 de marzo al 5 de febrero-11 de marzo (Carnaval)',
       '30 de enero-5 de marzo al 3 de febrero-9 de marzo (Carnaval)',
       '30 de enero-5 de marzo al 7 de febrero-13 de marzo (Carnaval)',
       '1-7 al 4-10 de febrero', 'Fin de semana próximo al 14 de febrero',
       'Febrero', 'Primer domingo de marzo',
       'Algunos sábados y todos los domingos y festivos desde el inicio de la Cuaresma hasta la primera semana de mayo (excepto Domingo de Ramos, Viernes Santo y Lunes de Pascua)',
       'Del 15 al 19 de marzo', 'Del 14 al 19 de marzo',
       'Del 15 al 31 de marzo', 'Fin de semana cercano al 28 de marzo',
       'Abril', 'Del segundo lunes al tercer domingo de abril',
       'Domingo de Ramos', 'Jueves y Viernes Santo',
       'Domingo de Ramos, Jueves y Viernes Santo', 'Viernes Santo',
       'Sábado Santo', 'Domingo de Resurrección', 'Semana Santa',
       'Miércoles Santo', 'Sábado posterior a Semana Santa',
       'Del 22 al 25 de abril', '27 de abril',
       'Último fin de semana de abril', 'Último domingo de abril',
       'Primera quincena de mayo', 'Del 30 de abril al 1 de mayo',
       'Del 30 de abril al 6 de mayo', '2 de mayo',
       'Primer viernes de mayo', 'Primer fin de semana de mayo',
       'Del 2 al 3 de mayo', 'Primer domingo de mayo',
       'Segunda o tercera semana de mayo', 'Domingo de Pentecostés',
       'Lunes de Pentecostés', '26 de mayo', 'Última semana de mayo',
       'Última semana de mayo-primera semana de junio',
       'Del 9 al 11 de junio', 'Corpus Christi',
       'Ocho días después de Corpus Christi', 'Mediados de junio',
       'Tercer fin de semana de junio', 'Del 24 al 29 de junio',
       '24 de junio', 'julio-agosto', 'Primer sábado de julio',
       'Del 4 al 12 de julio', 'Segundo fin de semana de julio',
       'Semana en torno al 17 de julio', 'Segunda quincena de julio',
       'Último sábado de julio', 'Semana entorno al 25 de julio',
       'En julio, cada cinco años', 'Agosto', 'Primer sábado de agosto',
       'Primer domingo de agosto', 'Primera semana de agosto',
       'Primera semana de agosto en los años impares, en los años pares se celebra en Oloron-Sainte-Marie',
       'Principios de agosto', '6 de agosto', 'Del 9 al 15 de agosto',
       'Del 14 al 17 de agosto', 'Del 14 al 21 de agosto',
       'Segundo domingo de agosto', '15 de agosto', '16 de agosto',
       'Segunda quincena de agosto', 'Del 20 al 23 de agosto',
       'Tercer sábado de agosto', 'Tercer domingo de agosto, cada 6 años',
       '27 de agosto', 'Último viernes de agosto',
       'Último viernes y sábado de agosto', 'Última semana de agosto',
       'Último domingo de agosto',
       'Madrugada siguiente al último domingo de agosto',
       'Último fin de semana deagosto y primer fin de semana de septiembre',
       '5-8 de septiembre', '8 de septiembre', 'Del 4 al 9 de septiembre',
       'Primera quincena de septiembre', '8 y 9 de septiembre',
       'Segundo domingo de septiembre', 'Del 12 al 15 de septiembre',
       'Del 15 al 24 de septiembre', '19 de septiembre',
       'Del 20 al 26 de septiembre', '24 de septiembre',
       '27 de septiembre', 'En torno al 27 de septiembre',
       'Último sábado de septiembre', 'Otoño', 'Octubre',
       'Principios de octubre', 'Del 4 al 12 de octubre',
       'Semana en torno al 9 de octubre', '12 de octubre',
       'Segunda quincena de octubre', 'Noviembre', '1 de noviembre',
       'Fin de semana más cercano al 1 de noviembre',
       '30 de noviembre-8 de diciembre', 'Del 5 al 8 de diciembre'],
      dtype=object)

In [25]:
from datetime import datetime

def add_carnival_dates(date):
    if date == '2-8 de enero (primer domingo de enero después de Año Nuevo)':
        start = datetime(2023, 1, 2)
        fin = datetime(2023, 1, 8)
        return pd.Series({'start': start, 'fin': fin})
    if date == '5 de enero':
        start = datetime(2023, 1, 5)
        fin = datetime(2023, 1, 5)  
        return pd.Series({'start': start, 'fin': fin})
    if date == 'Noche del 16 de enero':
        start = datetime(2023, 1, 15)
        fin = datetime(2023, 1, 16)    
        return pd.Series({'start': start, 'fin': fin})
    if date == '16, 17 y 18 de enero':
        start = datetime(2023, 1, 16)
        fin = datetime(2023, 1, 18)
        return pd.Series({'start': start, 'fin': fin})
    if date == '1 de enero':
        start = datetime(2023, 1, 1)
        fin = datetime(2023, 1, 1)
        return pd.Series({'start': start, 'fin': fin})   
    if date == '19 y 20 de enero':
        start = datetime(2023, 1, 19)
        fin = datetime(2023, 1, 20)
        return pd.Series({'start': start, 'fin': fin})
    if date == '20 y 21 de enero':
        start = datetime(2023, 1, 20)
        fin = datetime(2023, 1, 21)
        return pd.Series({'start': start, 'fin': fin})
    if date == '25-31 de enero (último domingo de enero)':
        start = datetime(2023, 1, 25)
        fin = datetime(2023, 1, 30)
        return pd.Series({'start': start, 'fin': fin})
    if date == '11 de enero-15 de febrero al 8 de febrero-14 de marzo (Carnaval)':
        start = datetime(2023, 2, 8)
        fin = datetime(2023, 3, 14)
        return pd.Series({'start': start, 'fin': fin})
    if date == '18 de enero-1 de marzo al 9 de febrero-12 de marzo (Carnaval)':
        start = datetime(2023, 1, 18)
        fin = datetime(2023, 3, 1)
        return pd.Series({'start': start, 'fin': fin})
    if date == '21 de enero-25 de febrero al 8 de febrero-14 de marzo (Carnaval)':
        start = datetime(2023, 1, 21)
        fin = datetime(2023, 2, 25)
        return pd.Series({'start': start, 'fin': fin})
    if date == '24 de enero-28 de febrero al 4 de febrero-10 de marzo (Carnaval)':
        start = datetime(2023, 1, 24)
        fin = datetime(2023, 2, 28)
        return pd.Series({'start': start, 'fin': fin})   
    if date == '24 de enero-28 de febrero (sábado anterior a Carnaval)':
        start = datetime(2023, 1, 24)
        fin = datetime(2023, 2, 28)
        return pd.Series({'start': start, 'fin': fin})
    if date == '25 de enero-29 de febrero (domingo anterior a Carnaval)':
        start = datetime(2023, 1, 25)
        fin = datetime(2023, 2, 28)
        return pd.Series({'start': start, 'fin': fin})
    if date == '29 de enero-4 de marzo al 5 de febrero-11 de marzo (Carnaval)':
        start = datetime(2023, 1, 29)
        fin = datetime(2023, 3, 11)
        return pd.Series({'start': start, 'fin': fin})       
    if date == '30 de enero-5 de marzo al 3 de febrero-9 de marzo (Carnaval)':
        start = datetime(2023, 1, 30)
        fin = datetime(2023, 3, 9)
        return pd.Series({'start': start, 'fin': fin})
    if date == '30 de enero-5 de marzo al 7 de febrero-13 de marzo (Carnaval)':
        start = datetime(2023, 1, 30)
        fin = datetime(2023, 3, 13)
        return pd.Series({'start': start, 'fin': fin})
    if date == '1-7 al 4-10 de febrero':
        start = datetime(2023, 2, 7)
        fin = datetime(2023, 2, 10)
        return pd.Series({'start': start, 'fin': fin})
    if date == 'Fin de semana próximo al 14 de febrero':
        start = datetime(2023, 2, 17)
        fin = datetime(2023, 2, 18)
        return pd.Series({'start': start, 'fin': fin})
    if date == 'Febrero':
        start = datetime(2023, 2, 1)
        fin = datetime(2023, 2, 28)
        return pd.Series({'start': start, 'fin': fin})  
    if date == 'Primer domingo de marzo':
        start = datetime(2023, 3, 4)
        fin = datetime(2023, 3, 5)
        return pd.Series({'start': start, 'fin': fin})    
    if date == 'Algunos sábados y todos los domingos y festivos desde el inicio de la Cuaresma hasta la primera semana de mayo (excepto Domingo de Ramos, Viernes Santo y Lunes de Pascua)':
        start = datetime(2023, 4, 2)
        fin = datetime(2023, 4, 14)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 15 al 19 de marzo':
        start = datetime(2023, 3, 15)
        fin = datetime(2023, 3, 19)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 14 al 19 de marzo':
        start = datetime(2023, 3, 14)
        fin = datetime(2023, 3, 19)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 15 al 31 de marzo':
        start = datetime(2023, 4, 15)
        fin = datetime(2023, 4, 30)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Fin de semana cercano al 28 de marzo':
        start = datetime(2023, 3, 24)
        fin = datetime(2023, 3, 25)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Abril':
        start = datetime(2023, 4, 1)
        fin = datetime(2023, 4, 30)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Del segundo lunes al tercer domingo de abril':
        start = datetime(2023, 4, 17)
        fin = datetime(2023, 4, 17)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Domingo de Ramos':
        start = datetime(2023, 4, 2)
        fin = datetime(2023, 4, 2)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Jueves y Viernes Santo':
        start = datetime(2023, 4, 7)
        fin = datetime(2023, 4, 10)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Domingo de Ramos, Jueves y Viernes Santo':
        start = datetime(2023, 4, 2)
        fin = datetime(2023, 4, 10)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Viernes Santo':
        start = datetime(2023, 4, 7)
        fin = datetime(2023, 4, 7)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Sábado Santo':
        start = datetime(2023, 4, 8)
        fin = datetime(2023, 4, 8)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Domingo de Resurrección':
        start = datetime(2023, 4, 9)
        fin = datetime(2023, 4, 9)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Semana Santa':
        start = datetime(2023, 4, 2)
        fin = datetime(2023, 4, 9)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Miércoles Santo':
        start = datetime(2023, 4, 5)
        fin = datetime(2023, 4, 5)
        return pd.Series({'start': start, 'fin': fin})    
    if date == 'Sábado posterior a Semana Santa':
        start = datetime(2023, 4, 1)
        fin = datetime(2023, 4, 1)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 22 al 25 de abril':
        start = datetime(2023, 4, 22)
        fin = datetime(2023, 4, 25)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == '27 de abril':
        start = datetime(2023, 4, 27)
        fin = datetime(2023, 4, 27)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Último fin de semana de abril':
        start = datetime(2023, 4, 28)
        fin = datetime(2023, 4, 29)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Último domingo de abril':
        start = datetime(2023, 4, 29)
        fin = datetime(2023, 4, 29)
        return pd.Series({'start': start, 'fin': fin})         
    if date == 'Primera quincena de mayo':
        start = datetime(2023, 5, 1)
        fin = datetime(2023, 5, 15)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 30 de abril al 1 de mayo':
        start = datetime(2023, 4, 30)
        fin = datetime(2023, 5, 1)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Del 30 de abril al 6 de mayo':
        start = datetime(2023, 4, 30)
        fin = datetime(2023, 5, 6)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '2 de mayo':
        start = datetime(2023, 5, 2)
        fin = datetime(2023, 5, 2)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primer viernes de mayo':
        start = datetime(2023, 5, 4)
        fin = datetime(2023, 5, 4)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primer fin de semana de mayo':
        start = datetime(2023, 5, 6)
        fin = datetime(2023, 5, 7)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 2 al 3 de mayo':
        start = datetime(2023, 5, 2)
        fin = datetime(2023, 5, 3)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Primer domingo de mayo':
        start = datetime(2023, 4, 30)
        fin = datetime(2023, 5, 6)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '2 de mayo':
        start = datetime(2023, 5, 2)
        fin = datetime(2023, 5, 2)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primer viernes de mayo':
        start = datetime(2023, 5, 1)
        fin = datetime(2023, 5, 1)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Segunda o tercera semana de mayo':
        start = datetime(2023, 5, 8)
        fin = datetime(2023, 5, 14)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Domingo de Pentecostés':
        start = datetime(2023, 5, 28)
        fin = datetime(2023, 5, 28)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Lunes de Pentecostés':
        start = datetime(2023, 5, 29)
        fin = datetime(2023, 5, 29)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '26 de mayo':
        start = datetime(2023, 5, 26)
        fin = datetime(2023, 5, 26)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Última semana de mayo':
        start = datetime(2023, 5, 22)
        fin = datetime(2023, 5, 28)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Última semana de mayo-primera semana de junio':
        start = datetime(2023, 5, 29)
        fin = datetime(2023, 6, 4)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 9 al 11 de junio':
        start = datetime(2023, 6, 9)
        fin = datetime(2023, 6, 11)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Ocho días después de Corpus Christi':
        start = datetime(2023, 6, 9)
        fin = datetime(2023, 6, 17)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Mediados de junio':
        start = datetime(2023, 6, 15)
        fin = datetime(2023, 6, 17)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Tercer fin de semana de junio':
        start = datetime(2023, 6, 19)
        fin = datetime(2023, 6, 25)
        return pd.Series({'start': start, 'fin': fin})      
    if date == 'Del 24 al 29 de junio':
        start = datetime(2023,6, 24)
        fin = datetime(2023, 6, 29)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Corpus Christi':
        start = datetime(2023, 6, 8)
        fin = datetime(2023, 6, 8)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == '24 de junio':
        start = datetime(2023, 6, 24)
        fin = datetime(2023, 6, 24)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'julio-agosto':
        start = datetime(2023, 7, 25)
        fin = datetime(2023, 8, 5)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primer sábado de julio':
        start = datetime(2023, 7, 1)
        fin = datetime(2023, 7, 1)
        return pd.Series({'start': start, 'fin': fin})        
    if date == 'Del 4 al 12 de julio':
        start = datetime(2023, 7, 4)
        fin = datetime(2023, 7, 12)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Segundo fin de semana de julio':
        start = datetime(2023, 7, 7)
        fin = datetime(2023, 7, 8)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Semana en torno al 17 de julio':
        start = datetime(2023, 7, 15)
        fin = datetime(2023, 7, 17)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Segunda quincena de julio':
        start = datetime(2023, 7, 15)
        fin = datetime(2023, 7, 30)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Último sábado de julio':
        start = datetime(2023, 7, 29)
        fin = datetime(2023, 7, 29)
        return pd.Series({'start': start, 'fin': fin})        
    if date == 'Semana entorno al 25 de julio':
        start = datetime(2023, 7, 22)
        fin = datetime(2023, 7, 25)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'En julio, cada cinco años':
        start = datetime(2023, 7, 22)
        fin = datetime(2023, 7, 27)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Agosto':
        start = datetime(2023, 8, 1)
        fin = datetime(2023, 8, 15)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primer sábado de agosto':
        start = datetime(2023, 8, 5)
        fin = datetime(2023, 8, 5)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primer domingo de agosto':
        start = datetime(2023, 8, 6)
        fin = datetime(2023, 8, 6)
        return pd.Series({'start': start, 'fin': fin})        
    if date == 'Primera semana de agosto':
        start = datetime(2023, 8, 7)
        fin = datetime(2023, 8, 13)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primera semana de agosto en los años impares, en los años pares se celebra en Oloron-Sainte-Marie':
        start = datetime(2023, 8, 7)
        fin = datetime(2023, 8, 14)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Principios de agosto':
        start = datetime(2023, 8, 1)
        fin = datetime(2023, 8, 10)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '6 de agosto':
        start = datetime(2023, 8, 6)
        fin = datetime(2023, 8, 6)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 9 al 15 de agosto':
        start = datetime(2023, 8, 9)
        fin = datetime(2023, 8, 15)
        return pd.Series({'start': start, 'fin': fin})
    if date == 'Del 14 al 17 de agosto':
        start = datetime(2023, 8, 14)
        fin = datetime(2023, 8, 17)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 14 al 21 de agosto':
        start = datetime(2023, 8, 14)
        fin = datetime(2023, 8, 21)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Segundo domingo de agosto':
        start = datetime(2023, 8, 15)
        fin = datetime(2023, 8, 15)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '15 de agosto':
        start = datetime(2023, 8, 15)
        fin = datetime(2023, 8, 15)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '16 de agosto':
        start = datetime(2023, 8, 16)
        fin = datetime(2023, 8, 16)
        return pd.Series({'start': start, 'fin': fin})    
    if date == 'Segunda quincena de agosto':
        start = datetime(2023, 8, 15)
        fin = datetime(2023, 8, 30)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 20 al 23 de agosto':
        start = datetime(2023, 8, 20)
        fin = datetime(2023, 8, 23)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Tercer sábado de agosto':
        start = datetime(2023, 8, 19)
        fin = datetime(2023, 8, 19)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Tercer domingo de agosto, cada 6 años':
        start = datetime(2023, 8, 22)
        fin = datetime(2023, 8, 22)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '27 de agosto':
        start = datetime(2023, 8, 27)
        fin = datetime(2023, 8, 27)
        return pd.Series({'start': start, 'fin': fin})    
    if date == 'Último viernes de agosto':
        start = datetime(2023, 8, 25)
        fin = datetime(2023, 8, 25)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Último viernes y sábado de agosto':
        start = datetime(2023, 8, 25)
        fin = datetime(2023, 8, 26)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Última semana de agosto':
        start = datetime(2023, 8, 23)
        fin = datetime(2023, 8, 29)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Último domingo de agosto':
        start = datetime(2023, 8, 29)
        fin = datetime(2023, 8, 29)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Madrugada siguiente al último domingo de agosto':
        start = datetime(2023, 8, 30)
        fin = datetime(2023, 8, 30)
        return pd.Series({'start': start, 'fin': fin})    
    if date == 'Último fin de semana deagosto y primer fin de semana de septiembre':
        start = datetime(2023, 8, 30)
        fin = datetime(2023, 9, 3)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '5-8 de septiembre':
        start = datetime(2023, 9, 5)
        fin = datetime(2023, 9, 8)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == '8 de septiembre':
        start = datetime(2023, 9, 8)
        fin = datetime(2023, 9, 8)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 4 al 9 de septiembre':
        start = datetime(2023, 9, 4)
        fin = datetime(2023, 9, 9)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Primera quincena de septiembre':
        start = datetime(2023, 9, 1)
        fin = datetime(2023, 9, 15)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == '8 y 9 de septiembre':
        start = datetime(2023, 9, 8)
        fin = datetime(2023, 9, 9)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Segundo domingo de septiembre':
        start = datetime(2023, 9, 10)
        fin = datetime(2023, 9, 10)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Del 12 al 15 de septiembre':
        start = datetime(2023, 9, 12)
        fin = datetime(2023, 9, 15)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 15 al 24 de septiembre':
        start = datetime(2023, 9, 15)
        fin = datetime(2023, 9, 24)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '19 de septiembre':
        start = datetime(2023, 9, 19)
        fin = datetime(2023, 9, 19)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Del 20 al 26 de septiembre':
        start = datetime(2023, 9, 20)
        fin = datetime(2023, 9, 26)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '24 de septiembre':
        start = datetime(2023, 9, 24)
        fin = datetime(2023, 9, 24)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == '27 de septiembre':
        start = datetime(2023, 9, 27)
        fin = datetime(2023, 9, 27)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'En torno al 27 de septiembre':
        start = datetime(2023, 9, 25)
        fin = datetime(2023, 9, 27)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Último sábado de septiembre':
        start = datetime(2023, 9, 30)
        fin = datetime(2023, 9, 30)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Otoño':
        start = datetime(2023, 9, 15)
        fin = datetime(2023, 10, 15)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Octubre':
        start = datetime(2023, 10, 1)
        fin = datetime(2023, 10, 15)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Principios de octubre':
        start = datetime(2023, 10, 1)
        fin = datetime(2023, 10, 10)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 4 al 12 de octubre':
        start = datetime(2023, 10, 4)
        fin = datetime(2023, 10, 12)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Semana en torno al 9 de octubre':
        start = datetime(2023, 10, 6)
        fin = datetime(2023, 10, 9)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == '12 de octubre':
        start = datetime(2023, 9, 12)
        fin = datetime(2023, 10, 12)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Segunda quincena de octubre':
        start = datetime(2023, 10, 16)
        fin = datetime(2023, 10, 30)
        return pd.Series({'start': start, 'fin': fin}) 
    if date == 'Noviembre':
        start = datetime(2023, 11, 1)
        fin = datetime(2023, 11, 10)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '1 de noviembre':
        start = datetime(2023, 11, 1)
        fin = datetime(2023, 11, 1)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Fin de semana más cercano al 1 de noviembre':
        start = datetime(2023, 11, 3)
        fin = datetime(2023, 11, 5)
        return pd.Series({'start': start, 'fin': fin})     
    if date == '30 de noviembre-8 de diciembre':
        start = datetime(2023, 11, 30)
        fin = datetime(2023, 12, 8)
        return pd.Series({'start': start, 'fin': fin})     
    if date == 'Del 5 al 8 de diciembre':
        start = datetime(2023, 12, 5)
        fin = datetime(2023, 12, 8)
        return pd.Series({'start': start, 'fin': fin})     
    
    else:
        return pd.Series({'start': None, 'fin': None})

data = pd.concat([data, data['date_start'].apply(add_carnival_dates)], axis=1)
data['start'] = pd.to_datetime(data['start'])
data['fin'] = pd.to_datetime(data['fin'])

data.head()

,festival,localidad,date_start,est,prov,latitude,longitude,start,fin
0,El Bautizo del Niño,Palencia,1 de enero,2015,Palencia,42.01667,-4.53333,2023-01-01,2023-01-01
1,La Vijanera,Silió,2-8 de enero (primer domingo de enero después ...,2009,Cantabria,43.14806,-4.02139,2023-01-02,2023-01-08
2,Cabalgata de Reyes Magos de Alcoy,Alcoy,5 de enero,2001,Alicante,38.69833,-0.47361,2023-01-05,2023-01-05
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar,5 de enero,2009,Cantabria,43.39333,-4.10472,2023-01-05,2023-01-05
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,Noche del 16 de enero,2019,Jaén,37.76972,-3.78889,2023-01-15,2023-01-16

In [26]:
data = data.drop(columns=['date_start'])
data.head()

,festival,localidad,est,prov,latitude,longitude,start,fin
0,El Bautizo del Niño,Palencia,2015,Palencia,42.01667,-4.53333,2023-01-01,2023-01-01
1,La Vijanera,Silió,2009,Cantabria,43.14806,-4.02139,2023-01-02,2023-01-08
2,Cabalgata de Reyes Magos de Alcoy,Alcoy,2001,Alicante,38.69833,-0.47361,2023-01-05,2023-01-05
3,Auto Sacramental y Cabalgata de Reyes,Santillana del Mar,2009,Cantabria,43.39333,-4.10472,2023-01-05,2023-01-05
4,Fiestas de San Antón y Carrera Urbana Internac...,Jaén,2019,Jaén,37.76972,-3.78889,2023-01-15,2023-01-16

In [27]:
data.to_csv(r'C:\WORK_IAAC\submissions\Storytelling\fiesta_shapefiles\fiestas_national_fin.csv')